---
title: "pivot_lobsters"
author: "Ankit Sharma"
date: "22/06/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

library(tidyverse)
library(readxl)
library(here)
library(skimr) 
library(kableExtra) 

lobsters <- read_xlsx(here("data/lobsters2.xlsx"), skip=4)
skimr::skim(lobsters)

lobsters %>%
group_by(year) %>%
summarize(count_by_year = n())

lobsters %>%
group_by(site, year) %>%
summarize(count_by_siteyear = n())


 
lobsters %>%
group_by(site, year) %>%
summarize(count_by_siteyear = n(), mean_size_mm = mean(size_mm))
 


 
siteyear_summary <- lobsters %>%
group_by(site, year) %>%
summarize(count_by_siteyear = n(),mean_size_mm = mean(size_mm, na.rm=TRUE), sd_size_mm = sd(size_mm, na.rm=TRUE))
 


 
siteyear_summary %>%
kable ()
 


 
siteyear_summary <- lobsters %>%
group_by(site, year) %>%
summarize(count_by_siteyear = n(),
          mean_size_mm = mean(size_mm, na.rm=TRUE), 
          sd_size_mm = sd(size_mm, na.rm=TRUE),
          median_size_mm = median(size_mm, na.rm=TRUE)
          )
          
ggplot(data = siteyear_summary, aes(x = year, y = count_by_siteyear, color = site)) +
  geom_line() 
  
ggsave(here("figures", "lobsters-line.png"))


ggplot(siteyear_summary, aes(x = year, y = median_size_mm)) +
  geom_col() +
  facet_wrap(~site)
ggsave(here("figures", "lobsters-col.png"))

lobsters %>%
count(site,year)
 

lobsters %>%
  mutate(size_m = size_mm / 1000)


lobsters_detailed <- lobsters %>%
  mutate(size_m = size_mm / 1000, 
         millenia = 2000,
         observer = "Allison Horst")

lobsters_detailed %>%
  select(date, site, size_m)


